version: "3.9"
services:
  cassandra:
    image: "cassandra:4.1.2"
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=Reducurl
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
